tls:
  certificates:
    - certFile: /certs/local-dev.crt
      keyFile: /certs/local-dev.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/local-dev.crt
        keyFile: /certs/local-dev.key

http:
  routers:
    forgejo:
      rule: Host(`forgejo.dev`)
      entryPoints: [websecure]
      tls: {}
      service: forgejo
    sonarqube:
      rule: Host(`sonar.dev`)
      entryPoints: [websecure]
      tls: {}
      service: sonarqube
    rancher:
      rule: Host(`rancher.dev`)
      entryPoints: [websecure]
      tls: {}
      service: rancher
    chartmuseum:
      rule: Host(`helm.dev`)
      entryPoints: [websecure]
      tls: {}
      service: chartmuseum
    go-loose:
      rule: Host(`auth.dev`) || HostRegexp(`[a-z0-9-]+\.auth\.dev`)
      entryPoints: [websecure]
      tls: {}
      service: go-loose
    go-guess:
      rule: HostRegexp(`[a-z0-9-]+\.guess\.dev`)
      entryPoints: [websecure]
      tls: {}
      service: go-guess
  services:
    forgejo:
      loadBalancer:
        servers:
          - url: http://forgejo:3000
    sonarqube:
      loadBalancer:
        servers:
          - url: http://sonarqube:9000
    rancher:
      loadBalancer:
        servers:
          - url: http://rancher:80
    chartmuseum:
      loadBalancer:
        servers:
          - url: http://chartmuseum:8080
    go-loose:
      loadBalancer:
        servers:
          - url: http://go-loose:8080
    go-guess:
      loadBalancer:
        servers:
          - url: http://go-guess-web:80
